# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import definition_pb2 as proto_dot_definition__pb2


class DBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PerformBackup = channel.unary_unary(
                '/utility.DB/PerformBackup',
                request_serializer=proto_dot_definition__pb2.Message.SerializeToString,
                response_deserializer=proto_dot_definition__pb2.MessageResponse.FromString,
                )
        self.PerformRestore = channel.unary_unary(
                '/utility.DB/PerformRestore',
                request_serializer=proto_dot_definition__pb2.Message.SerializeToString,
                response_deserializer=proto_dot_definition__pb2.MessageResponse.FromString,
                )
        self.PerformReplication = channel.unary_unary(
                '/utility.DB/PerformReplication',
                request_serializer=proto_dot_definition__pb2.Message.SerializeToString,
                response_deserializer=proto_dot_definition__pb2.MessageResponse.FromString,
                )


class DBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PerformBackup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PerformRestore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PerformReplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PerformBackup': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformBackup,
                    request_deserializer=proto_dot_definition__pb2.Message.FromString,
                    response_serializer=proto_dot_definition__pb2.MessageResponse.SerializeToString,
            ),
            'PerformRestore': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformRestore,
                    request_deserializer=proto_dot_definition__pb2.Message.FromString,
                    response_serializer=proto_dot_definition__pb2.MessageResponse.SerializeToString,
            ),
            'PerformReplication': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformReplication,
                    request_deserializer=proto_dot_definition__pb2.Message.FromString,
                    response_serializer=proto_dot_definition__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'utility.DB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PerformBackup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/utility.DB/PerformBackup',
            proto_dot_definition__pb2.Message.SerializeToString,
            proto_dot_definition__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PerformRestore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/utility.DB/PerformRestore',
            proto_dot_definition__pb2.Message.SerializeToString,
            proto_dot_definition__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PerformReplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/utility.DB/PerformReplication',
            proto_dot_definition__pb2.Message.SerializeToString,
            proto_dot_definition__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
