# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/fs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import definition_pb2 as proto_dot_definition__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproto/fs.proto\x12\x07utility\x1a\x16proto/definition.proto2\xfe\x01\n\x02\x46S\x12;\n\x0bRemoveCache\x12\x10.utility.Message\x1a\x18.utility.MessageResponse\"\x00\x12;\n\x0bResizeImage\x12\x10.utility.Message\x1a\x18.utility.MessageResponse\"\x00\x12=\n\rCompressImage\x12\x10.utility.Message\x1a\x18.utility.MessageResponse\"\x00\x12?\n\x0f\x43ompressArchive\x12\x10.utility.Message\x1a\x18.utility.MessageResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.fs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FS._serialized_start=52
  _FS._serialized_end=306
# @@protoc_insertion_point(module_scope)
