# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import definition_pb2 as proto_dot_definition__pb2


class FSStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RemoveCache = channel.unary_unary(
                '/utility.FS/RemoveCache',
                request_serializer=proto_dot_definition__pb2.Message.SerializeToString,
                response_deserializer=proto_dot_definition__pb2.MessageResponse.FromString,
                )
        self.ResizeImage = channel.unary_unary(
                '/utility.FS/ResizeImage',
                request_serializer=proto_dot_definition__pb2.Message.SerializeToString,
                response_deserializer=proto_dot_definition__pb2.MessageResponse.FromString,
                )
        self.CompressImage = channel.unary_unary(
                '/utility.FS/CompressImage',
                request_serializer=proto_dot_definition__pb2.Message.SerializeToString,
                response_deserializer=proto_dot_definition__pb2.MessageResponse.FromString,
                )
        self.CompressArchive = channel.unary_unary(
                '/utility.FS/CompressArchive',
                request_serializer=proto_dot_definition__pb2.Message.SerializeToString,
                response_deserializer=proto_dot_definition__pb2.MessageResponse.FromString,
                )


class FSServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RemoveCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResizeImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompressImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompressArchive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RemoveCache': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveCache,
                    request_deserializer=proto_dot_definition__pb2.Message.FromString,
                    response_serializer=proto_dot_definition__pb2.MessageResponse.SerializeToString,
            ),
            'ResizeImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ResizeImage,
                    request_deserializer=proto_dot_definition__pb2.Message.FromString,
                    response_serializer=proto_dot_definition__pb2.MessageResponse.SerializeToString,
            ),
            'CompressImage': grpc.unary_unary_rpc_method_handler(
                    servicer.CompressImage,
                    request_deserializer=proto_dot_definition__pb2.Message.FromString,
                    response_serializer=proto_dot_definition__pb2.MessageResponse.SerializeToString,
            ),
            'CompressArchive': grpc.unary_unary_rpc_method_handler(
                    servicer.CompressArchive,
                    request_deserializer=proto_dot_definition__pb2.Message.FromString,
                    response_serializer=proto_dot_definition__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'utility.FS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FS(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RemoveCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/utility.FS/RemoveCache',
            proto_dot_definition__pb2.Message.SerializeToString,
            proto_dot_definition__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResizeImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/utility.FS/ResizeImage',
            proto_dot_definition__pb2.Message.SerializeToString,
            proto_dot_definition__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CompressImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/utility.FS/CompressImage',
            proto_dot_definition__pb2.Message.SerializeToString,
            proto_dot_definition__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CompressArchive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/utility.FS/CompressArchive',
            proto_dot_definition__pb2.Message.SerializeToString,
            proto_dot_definition__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
